package com.flying.xiaopo.lab.ui;

import com.flying.xiaopo.lab.model.SnippetFile;
import com.intellij.ui.components.JBLabel;
import com.intellij.util.ui.UIUtil;
import java.awt.BorderLayout;
import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.JComponent;
import javax.swing.JPanel;

/**
 * TODO UI 修改
 *
 * @author wupanjie on 2017/10/26.
 */
public class SnippetCell {
  public JPanel rootPanel;
  public JBLabel labelName;
  public JBLabel labelDate;
  public JBLabel labelCategory;
  private SnippetFile snippetFile;

  public SnippetCell() {
    init();
  }

  private void init() {
    labelName.setComponentStyle(UIUtil.ComponentStyle.LARGE);
    labelCategory.setForeground(Color.BLUE);
    labelCategory.setComponentStyle(UIUtil.ComponentStyle.SMALL);
    labelDate.setComponentStyle(UIUtil.ComponentStyle.SMALL);
  }

  public void bind(SnippetFile snippetFile, boolean isSelected) {
    this.snippetFile = snippetFile;
    labelName.setText(snippetFile.getName());
    labelCategory.setText(snippetFile.getCategoryName());
    labelDate.setText(snippetFile.getCreateDate());

    if (isSelected) {
      labelName.setForeground(Color.RED);
    }
  }

  {
    // GUI initializer generated by IntelliJ IDEA GUI Designer
    // >>> IMPORTANT!! <<<
    // DO NOT EDIT OR ADD ANY CODE HERE!
    $$$setupUI$$$();
  }

  /**
   * Method generated by IntelliJ IDEA GUI Designer >>> IMPORTANT!! <<< DO NOT edit this method OR
   * call it in your code!
   *
   * @noinspection ALL
   */
  private void $$$setupUI$$$() {
    rootPanel = new JPanel();
    rootPanel.setLayout(new BorderLayout(0, 0));
    rootPanel.setBorder(
        BorderFactory.createTitledBorder(BorderFactory.createEmptyBorder(10, 10, 10, 10), null));
    labelName = new JBLabel();
    labelName.setForeground(new Color(-16777216));
    rootPanel.add(labelName, BorderLayout.NORTH);
    final JPanel panel1 = new JPanel();
    panel1.setLayout(new BorderLayout(0, 0));
    rootPanel.add(panel1, BorderLayout.CENTER);
    panel1.setBorder(
        BorderFactory.createTitledBorder(BorderFactory.createEmptyBorder(6, 0, 0, 0), null));
    labelCategory = new JBLabel();
    panel1.add(labelCategory, BorderLayout.WEST);
    labelDate = new JBLabel();
    panel1.add(labelDate, BorderLayout.EAST);
  }

  /** @noinspection ALL */
  public JComponent $$$getRootComponent$$$() {
    return rootPanel;
  }
}
